# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    fetchDepth: 5
  - task: NodeTool@0
    inputs:
      versionSpec: '22.4.0'
    displayName: 'Install Node.js'
  # - script: |
  #     npm install -g jsonlint-cli
  #     cat << EOF > .jsonlintrc
  #     {
  #     "validate": "",
  #     "ignore": ["node_modules/**/*"],
  #     "indent": "",
  #     "env": "json-schema-draft-04"
  #     }
  #     EOF
  #     jsonlint-cli **/*.json
  #     if [ "$?" -ne "0" ]
  #     then 
  #     Error=true
  #     echo ERROR STATUS $Error
  #     fi
  #     if [ $Error ]; then exit 1; fi 
  #   displayName: 'Run Node.js script'
  - script: |
      npm install ajv
      node validateJSON.js schemas/org-schema.json  api-sys-h2o-2-24678-h2o-vmware-com/Org1/Org.json
      # if [ "$?" -ne "0" ]
      # then 
      # Error=true
      # echo ERROR STATUS $Error
      # fi
      # if [ $Error ]; then exit 1; fi 
    displayName: 'Run Node.js script'
