# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    fetchDepth: 10
  - task: NodeTool@0
    inputs:
      versionSpec: '22.4.0'
    displayName: 'Install Node.js'
  # - script: |
  #     npm install -g jsonlint-cli
  #     cat << EOF > .jsonlintrc
  #     {
  #     "validate": "",
  #     "ignore": ["node_modules/**/*"],
  #     "indent": "",
  #     "env": "json-schema-draft-04"
  #     }
  #     EOF
  #     jsonlint-cli **/*.json
  #     if [ "$?" -ne "0" ]
  #     then 
  #     Error=true
  #     echo ERROR STATUS $Error
  #     fi
  #     if [ $Error ]; then exit 1; fi 
  #   displayName: 'Run Node.js script'
  - script: |
      npm install ajv
      files=`git diff --name-only HEAD HEAD~8 | grep '.json'`
      echo "FILES: "$files
    displayName: 'Run schema validation'
