---
org: Org-1
space: Space1
space-developer:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups: []
space-manager:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups: []
space-auditor:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups: []
space-supporter:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups: []
allow-ssh: true
enable-space-quota: false
enable-security-group: true
enable-unassign-security-group: true
enable-remove-users: false
isolation_segment: ""
named-security-groups:
  - Org-1_Space1
paid-service-plans-allowed: false
named_quota: ""
metadata:
  annotations: {}
  labels: {}