name: json-yaml-validate 
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  json-yaml-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: validate-org
        id: validate-org
        uses: GrantBirki/json-yaml-validate@v3.0.0
        with:
          yaml_schema: org-schema.yml
          files: |
            api-sys-h2o-2-24678-h2o-vmware-com/Org1/Org.yml
      # - name: validate-org-state
      #   id: validate-org-state
      #   uses: GrantBirki/json-yaml-validate@v3.0.0
      #   with:
      #     yaml_schema: org-state-schema.yml 
      #     files: |
      #       api-sys-h2o-2-24678-h2o-vmware-com/Org1/OrgState.yml






