on:
  push:
    paths:
      - '**.yml'
      - '**.yaml'
name: Validate YAML
jobs:
  releases-matrix:
    name: Validate YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RomanosTrechlis/actions-validate-yaml@master
        with:
          schema: spec.json
          data: |-
            api-sys-h2o-2-24678-h2o-vmware-com/GitOrgsList.yml
            api-sys-h2o-2-24678-h2o-vmware-com/OrgList.yml
